#-------------------------------
# Site Settings
title: Ann
logo: # You can add own logo. For example '/images/logo.png'.
author: Sian Ren
description: Sian Ren


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    # - title: 'Contact'
    #   url: '/contact/'
    # - title: 'Guide'
    #   url: '/guide/'
    - title: 'Tags'
      url: '/tags/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hello, my name’s Sian Ren. I’m a student at UCSD, majoring in Psychology.
  hero__description: I am a passionate art and art history enthusiast who delights in expressing ideas through drawing. My expertise in Psychology equips me with valuable insights beneficial in the fields of business and marketing. I invite you to navigate my portfolio and posts to know a bit more about me and my work.


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__gallery:
    - image: /images/an-1.jpeg
      title: Where title goes
      description: Where description goes <a href="Sian Ren">Sian Ren</a>

    - image: /images/an-2.jpeg
      title: Where title goes
      description: Where description goes <a href="Sian Ren">Sian Ren</a>

    - image: /images/an-3.jpeg
      title: Where title goes
      description: Where description goes <a href="Sian Ren">Sian Ren</a>

    - image: /images/an-4.jpeg
      title: Where title goes
      description: Where description goes <a href="Sian Ren">Sian Ren</a>

    - image: /images/an-5.jpeg
      title: Where title goes
      description: Where description goes <a href="Sian Ren">Sian Ren</a>

    - image: /images/an-6.jpeg
      title: Where title goes
      description: Where description goes <a href="Sian Ren">Sian Ren</a>

    # - image: /images/gallery-07.jpg
    #   title: Water Journal
    #   description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

    # - image: /images/gallery-08.jpg
    #   title: Luca Bravo
    #   description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

    # - image: /images/gallery-09.jpg
    #   title: Books and Laptop
    #   description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>


#-------------------------------
# Subscribe Settings
# mailchimp:
#   mailchimp__title: Get updates and digital art inspiration # Add your Title
#   mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#   mailchimp__button__text: Subscribe # Add your button text.
#   mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
- {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
# - {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
# - {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com"}
- {icon: "ion-logo-linkedin", color: "#0077b5", label: Linkedin, link: "https://linkedin.com"}
# - {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
# contact:
#   email: your@email.com # Add your email for contact form
#   description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

# disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
# google-analytics: # Add your GA Tracking Id